Mark repository as deprecated
RexOps/rex-recipes pull request #42
Opened 2019-10-19 20:04 UTC by ferki

This PR adds a notice to the README about its state.

@ehuelsmann: please review and let me know if there's anything to add or reword.

I decided to just simply prepend the deprecation notice, but we can also just replace the README completely if you think that's better.

2019-10-24 20:48 UTC, ehuelsmann commented on README.pod
> +A few people must maintain all the modules, including testing and reviews, and even if they are not the authors. That proved to be an unrealistic expectation.
s/ and / /
?

2019-10-24 20:49 UTC, ehuelsmann commented on README.pod
> +Once a module is merged, the author loses direct maintainership of it, since they can only interact with it via pull requests. They could be granted access to directly manage this repo, therefore all
s/not anyone/not what anyone/
?

2019-10-24 20:51 UTC, ehuelsmann commented
@ferki would it make sense to point people to a document (from the Perl community, not on our own site) which explains how to upload Perl modules to PAUSE/CPAN?

Another item: currently rexify has a way to "locally install" a module. Maybe we need to declare whether that will still work, but just download from CPAN or that it won't work anymore, or...?

2019-10-24 20:52 UTC, ehuelsmann requested changes
As per my comments, I think we'll want a few changes, potentially after discussion first.

2019-10-25 17:07 UTC, ferki commented on README.pod
> +A few people must maintain all the modules, including testing and reviews, and even if they are not the authors. That proved to be an unrealistic expectation.
Fixed

2019-10-25 17:08 UTC, ferki commented on README.pod
> +Once a module is merged, the author loses direct maintainership of it, since they can only interact with it via pull requests. They could be granted access to directly manage this repo, therefore all
Fixed

2019-10-25 17:28 UTC, ferki commented
> @ferki would it make sense to point people to a document (from the Perl community, not on our own site) which explains how to upload Perl modules to PAUSE/CPAN?

I've slightly reworded that part and included links.

> Another item: currently rexify has a way to "locally install" a module. Maybe we need to declare whether that will still work, but just download from CPAN or that it won't work anymore, or...?

Well, no code changes in that regard, so that works as before. It is already able to handle installing from CPAN and/or directly from git repos.

2019-10-25 17:30 UTC, ferki commented
@ehuelsmann: thanks for the review, I believe I've addressed/answered all items. Additional `fixup!` commits must be squashed away upon merging ;)

2019-10-25 17:50 UTC, ehuelsmann approved these changes
Yup. It's fine now!

2019-10-25 19:00 UTC, merged